DROP TABLE IF EXISTS words CASCADE;
DROP TABLE IF EXISTS definitions CASCADE;
DROP TABLE IF EXISTS user_picks CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS tags_map CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TYPE IF EXISTS lemma_type;
DROP TYPE IF EXISTS source_type;