package config_test

import (
	"testing"
	"time"

	"github.com/gamma-omg/lexi-go/internal/services/auth/internal/config"
	"github.com/stretchr/testify/assert"
)

func TestFromEnv(t *testing.T) {
	t.Setenv("HTTP_LISTEN_ADDR", "localhost")
	t.Setenv("HTTP_LISTEN_PORT", "9090")
	t.Setenv("HTTP_READ_TIMEOUT", "45s")
	t.Setenv("HTTP_WRITE_TIMEOUT", "45s")
	t.Setenv("HTTP_IDLE_TIMEOUT", "90s")
	t.Setenv("HTTP_SHUTDOWN_TIMEOUT", "15s")
	t.Setenv("JWT_ACCESS_SECRET", "access_secret")
	t.Setenv("JWT_REFRESH_SECRET", "refresh_secret")
	t.Setenv("JWT_ISSUER", "test-issuer")
	t.Setenv("JWT_ALGORITHM_ACCESS", "test-algorithm-access")
	t.Setenv("JWT_ALGORITHM_REFRESH", "test-algorithm-refresh")
	t.Setenv("JWT_ACCESS_TTL", "20m")
	t.Setenv("JWT_REFRESH_TTL", "14h")
	t.Setenv("DB_HOST", "dbhost")
	t.Setenv("DB_PORT", "5432")
	t.Setenv("DB_USER", "dbuser")
	t.Setenv("DB_PASSWORD", "dbpassword")
	t.Setenv("DB_NAME", "auth_service")
	t.Setenv("OAUTH_GOOGLE_CLIENT_ID", "google_client_id")
	t.Setenv("OAUTH_GOOGLE_CLIENT_SECRET", "google_client_secret")
	t.Setenv("OAUTH_GOOGLE_REDIRECT_URL", "http://localhost:9090/auth/google/callback")
	t.Setenv("OTC_REDIS_HOST", "redishost")
	t.Setenv("OTC_REDIS_PORT", "6380")
	t.Setenv("OTC_REDIS_PASSWORD", "redispassword")
	t.Setenv("OTC_REDIS_DB", "1")
	t.Setenv("OTC_CODE_TTL", "15m")

	cfg := config.FromEnv()

	assert.Equal(t, "localhost", cfg.HTTP.ListenAddr)
	assert.Equal(t, 9090, cfg.HTTP.ListenPort)
	assert.Equal(t, 45*time.Second, cfg.HTTP.ReadTimeout)
	assert.Equal(t, 45*time.Second, cfg.HTTP.WriteTimeout)
	assert.Equal(t, 90*time.Second, cfg.HTTP.IdleTimeout)
	assert.Equal(t, 15*time.Second, cfg.HTTP.ShutdownTimeout)
	assert.Equal(t, "access_secret", cfg.JWT.AccessSecret)
	assert.Equal(t, "refresh_secret", cfg.JWT.RefreshSecret)
	assert.Equal(t, 20*time.Minute, cfg.JWT.AccessTTL)
	assert.Equal(t, 14*time.Hour, cfg.JWT.RefreshTTL)
	assert.Equal(t, "test-issuer", cfg.JWT.Issuer)
	assert.Equal(t, "test-algorithm-access", cfg.JWT.AlgorithmAccess)
	assert.Equal(t, "test-algorithm-refresh", cfg.JWT.AlgorithmRefresh)
	assert.Equal(t, "dbhost", cfg.DB.Host)
	assert.Equal(t, "5432", cfg.DB.Port)
	assert.Equal(t, "dbuser", cfg.DB.User)
	assert.Equal(t, "dbpassword", cfg.DB.Password)
	assert.Equal(t, "auth_service", cfg.DB.Name)
	assert.Equal(t, "google_client_id", cfg.OAuth.Google.ClientID)
	assert.Equal(t, "google_client_secret", cfg.OAuth.Google.ClientSecret)
	assert.Equal(t, "http://localhost:9090/auth/google/callback", cfg.OAuth.Google.RedirectURL)
	assert.Equal(t, "redishost", cfg.RedisOTC.Host)
	assert.Equal(t, "6380", cfg.RedisOTC.Port)
	assert.Equal(t, "redispassword", cfg.RedisOTC.Password)
	assert.Equal(t, 1, cfg.RedisOTC.DB)
	assert.Equal(t, 15*time.Minute, cfg.RedisOTC.CodeTTL)
}

func TestFromEnv_Defaults(t *testing.T) {
	t.Setenv("JWT_ACCESS_SECRET", "default_access")
	t.Setenv("JWT_REFRESH_SECRET", "default_refresh")
	t.Setenv("OAUTH_GOOGLE_CLIENT_ID", "client_id")
	t.Setenv("OAUTH_GOOGLE_CLIENT_SECRET", "secret")
	cfg := config.FromEnv()

	assert.Equal(t, "", cfg.HTTP.ListenAddr)
	assert.Equal(t, 8080, cfg.HTTP.ListenPort)
	assert.Equal(t, 30*time.Second, cfg.HTTP.ReadTimeout)
	assert.Equal(t, 30*time.Second, cfg.HTTP.WriteTimeout)
	assert.Equal(t, 60*time.Second, cfg.HTTP.IdleTimeout)
	assert.Equal(t, 10*time.Second, cfg.HTTP.ShutdownTimeout)
	assert.Equal(t, "default_access", cfg.JWT.AccessSecret)
	assert.Equal(t, "default_refresh", cfg.JWT.RefreshSecret)
	assert.Equal(t, "lexigo-auth-service", cfg.JWT.Issuer)
	assert.Equal(t, "ES256", cfg.JWT.AlgorithmAccess)
	assert.Equal(t, "HS256", cfg.JWT.AlgorithmRefresh)
	assert.Equal(t, 15*time.Minute, cfg.JWT.AccessTTL)
	assert.Equal(t, 7*24*time.Hour, cfg.JWT.RefreshTTL)
	assert.Equal(t, "localhost", cfg.DB.Host)
	assert.Equal(t, "5432", cfg.DB.Port)
	assert.Equal(t, "postgres", cfg.DB.User)
	assert.Equal(t, "password", cfg.DB.Password)
	assert.Equal(t, "auth_service", cfg.DB.Name)
	assert.Equal(t, "client_id", cfg.OAuth.Google.ClientID)
	assert.Equal(t, "secret", cfg.OAuth.Google.ClientSecret)
	assert.Equal(t, "http://localhost:8080/auth/google/callback", cfg.OAuth.Google.RedirectURL)
	assert.Equal(t, "localhost", cfg.RedisOTC.Host)
	assert.Equal(t, "6379", cfg.RedisOTC.Port)
	assert.Equal(t, "", cfg.RedisOTC.Password)
	assert.Equal(t, 0, cfg.RedisOTC.DB)
	assert.Equal(t, 10*time.Second, cfg.RedisOTC.CodeTTL)
}
